# endere�o do banco no formato JDBC: jdbc:postgresql://host:porta/nome_do_banco
spring.datasource.url=${DB_URL}

# usuário do banco
spring.datasource.username=${DB_USERNAME}

# senha do banco
spring.datasource.password=${DB_PASSWORD}